name: Build and Deploy to Cloud Functions

on:
  push:
    branches:
      - main
      - feat/terraform

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_ARTIFACT: build
    outputs:
      build_artifact: ${{ env.BUILD_ARTIFACT }}
      version: ${{ steps.package_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get version
        id: package_version
        run: |
          PACKAGE_VERSION=$(cat package.json | jq -r '.version')
          echo "Current version: $PACKAGE_VERSION"
          echo "version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
      - name: Install dependencies
        run: yarn
      - name: Build
        id: build
        run: |
          yarn build
          echo "build_path=dist" >> $GITHUB_OUTPUT
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BUILD_ARTIFACT }}
          path: ${{ steps.build.outputs.build_path }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    env:
      TF_TOKEN_app_terraform_io: ${{ secrets.TF_API_TOKEN }}
      TF_VAR_source_filepath: /tmp/${{ needs.build.outputs.build_artifact }}/
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download build
        id: download_build
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.build_artifact }}
          path: ${{ env.TF_VAR_source_filepath }}
      - name: Terraform init
        run: terraform init
      - name: Terraform plan
        run: terraform plan -out ${{ needs.build.outputs.version }}
      - name: Terraform apply
        run: terraform apply ${{ needs.build.outputs.version }}
