name: Build and Deploy to Cloud Functions

on:
  push:
    branches:
      - main
      - feat/terraform

env:
  PROJECT_ID: crypto-alert-421018
  BUCKET_NAME: crypto-alert-serverless-gcf-source
  GCS_LOCATION: us-east1
  REGION: us-east1

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build_artifact: ${{ steps.package_version.outputs.version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Get version
        id: package_version
        run: |
          PACKAGE_VERSION=$(cat package.json | jq -r '.version')
          echo "Current version: $PACKAGE_VERSION"
          echo "version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.package_version.outputs.version }}
          path: dist

  upload:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: 'read'
      id-token: 'write'

    outputs:
      source_path: ${{ steps.upload-file.outputs.uploaded }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v2'
        with:
          token_format: 'access_token'
          project_id: ${{ env.PROJECT_ID }}
          workload_identity_provider: '${{ secrets.WIF_PROVIDER }}' # e.g. - projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider
          service_account: '${{ secrets.WIF_SERVICE_ACCOUNT }}' # e.g. - my-service-account@my-project.iam.gserviceaccount.com
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          version: '>= 472.0.0'
      - name: Create GCloud Bucket if not exist
        run: |
          if gcloud storage buckets describe "${{ env.BUCKET_NAME }}" &> /dev/null ; then
            echo "GCP Bucket ${{ env.BUCKET_NAME }} already exists"
          else
            echo "Creating GCP Bucket ${{ env.BUCKET_NAME }}"
            gcloud storage buckets create --location=us-east1 gs://${{ env.BUCKET_NAME }}
          fi
      - name: Download build
        uses: actions/download-artifact@v4
        with:
          name: ${{ needs.build.outputs.build_artifact }}
      - name: Upload build
        id: 'upload-file'
        uses: 'google-github-actions/upload-cloud-storage@v2'
        with:
          path: ${{ needs.build.outputs.build_artifact }}.zip
          destination: ${{ env.BUCKET_NAME }}

  deploy:
    runs-on: ubuntu-latest
    needs: upload
    steps:
      - name: Terraform init
        run: |
          export TF_TOKEN=${{ secrets.TF_API_TOKEN }}
          terraform init
      - name: Terraform apply
        run: |
          export TF_VAR_source_filepath=${{ needs.upload.outputs.source_path }}
          terraform apply
